-- 코드를 입력하세요

# SELECT ID,NAME,HOST_ID
# FROM PLACES
# WHERE HOST_ID=
# (SELECT HOST_ID, count(HOST_ID) AS A
# FROM PLACES
# GROUP BY HOST_ID
# HAVING A>1)

SELECT ID,NAME,HOST_ID
FROM PLACES
WHERE HOST_ID IN
(SELECT HOST_ID
FROM PLACES
GROUP BY HOST_ID
HAVING COUNT(HOST_ID)>1)