-- 코드를 입력하세요
SELECT a.APNT_NO, p.PT_NAME,p.PT_NO,a.MCDP_CD,d.DR_NAME,a.APNT_YMD
FROM APPOINTMENT A
JOIN PATIENT P ON A.PT_NO = P.PT_NO
JOIn DOCTOR D ON A.MDDR_ID = D.DR_ID
WHERE A.APNT_CNCL_YN = 'N' AND DATE_FORMAT(a.APNT_YMD,'%Y-%m-%d') ='2022-04-13' 
order by a.APNT_YMD ASC