WITH MEMBERCOUT AS(
SELECT MEMBER_ID,COUNT(*) AS C
FROM REST_REVIEW
GROUP BY MEMBER_ID
),
TOPREVIEW AS (SELECT MEMBER_ID
FROM MEMBERCOUT 
WHERE MEMBERCOUT.C = (SELECT MAX(MEMBERCOUT.C) FROM MEMBERCOUT)
)    
    
    
SELECT M.MEMBER_NAME, R.REVIEW_TEXT	,DATE_FORMAT(R.REVIEW_DATE,'%Y-%m-%d') as REVIEW_DATE
FROM REST_REVIEW R
JOIN MEMBER_PROFILE M ON R.MEMBER_ID = M.MEMBER_ID
JOIN TOPREVIEW T ON T.MEMBER_ID = R.MEMBER_ID
order by r.REVIEW_DATE, r.REVIEW_TEXT
