-- 코드를 입력하세요
SELECT distinct(C.car_id) 
From CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H on C.CAR_ID = H.CAR_ID
WHERE CAR_TYPE = '세단' AND DATE_FORMAT(START_DATE,'%m') = '10'
ORDER BY C.car_id desc 