
SELECT SUB_1.SCORE AS SCORE, SUB_1.EMP_NO, E.EMP_NAME,E.POSITION,E.EMAIL
FROM(
    SELECT  EMP_NO,SUM(SCORE) AS SCORE
    FROM HR_GRADE 
    GROUP BY EMP_NO) AS SUB_1
JOIN HR_EMPLOYEES E ON SUB_1.EMP_NO = E.EMP_NO
# JOIN HR_DEPARTMENT D ON E.DEPT_ID = D.DEPT_ID
ORDER BY SUB_1.SCORE DESC
LIMIT 1
